resources:
  - url: http://127.0.0.1:8000/flower-card.js
    type: module

views:
  - cards:
      - type: custom:flower-card
        entity: plant.basil
      - type: custom:flower-card
        entity: plant.basil
