resources:
  - url: http://127.0.0.1:5000/flower-card.js?v2
    type: module

views:
  - cards:
      - type: custom:flower-card
        entity: plant.basil
      - type: custom:flower-card
        entity: plant.basil
